# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1d99cd247f8d4b9e2a944d2d3a989ad8a3d9a01794b0437f808ce45c328833a71f74b3b6ca9c544fd4c77d482f03e16ade580ecd37c968ce47705455ca6f5d

test:
  secret_key_base: 06a3db01b4294b95fc41ae80e54cecfab38f3f49e0b57ecbb368a80e97abfb6a3be2cef60f31df36c458cc3bee85931fc35c3de74060fc2c2b0a4d9697b5aa86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
